import type { Metadata } from "next"
import { Oswald, Lato } from "next/font/google"
import "../styles/globals.css"
import Providers from "./providers"

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${oswald.variable} ${lato.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
